### ISSUE TITLE
CP-SAT max_time_in_seconds does not always work

### ISSUE THREAD

**Issue by Username159** [google/or-tools#2604]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: Python 3.7

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux Manjaro 20.1 and Google Colab in Chrome.

Sometimes the max_time_in_seconds is ignored.
Noticed this behaviour with 4, 6 and 8 threads.

Most of the time I set the max_time_in_seconds to something between 600 and 1800 seconds and also implemented the "Stopping a search after a specified number of solutions". 
In Google Colab I am having more problems with the max_time_in_seconds and with Linux and Visual Studio Code I am having more trouble with the solver stopping after x solutions.

It seems like the solver get stuck in a computationally/processor intensive operation/step and everything "freezes". When that happens I have to force it to stop and the progress is lost.

[model.zip](https://github.com/google/or-tools/files/6692710/model.zip)

#20 #2009

**Comment by lperron** [comment]
Can you send me the instruction to execute the model, or better export the model in proto format: `model.ExportToFile('issue2604.pb.txt')`

**Comment by Username159** [comment]
[issue2604.pb.txt](https://github.com/google/or-tools/files/6707317/issue2604.pb.txt)

Heres the model in proto format.

**Comment by lperron** [comment]
master, 8 threads, 600s time limit

CpSolverResponse summary:
status: FEASIBLE
objective: 120210
best_bound: 92981
booleans: 15989
conflicts: 2062185
branches: 4053990
propagations: 561669180
integer_propagations: 383625199
restarts: 23611
lp_iterations: 0
walltime: 600.376
usertime: 600.376
deterministic_time: 1162.87
primal_integral: 11879.8

I cannot reproduce the problem. I will make some more runs.

**Comment by Username159** [comment]
[issue2604.pb.txt](https://github.com/google/or-tools/files/6724563/issue2604.pb.txt)


Here is the same model with some different input data. Still having the problem that the solver doesn't stop after 75 solutions (or 36*60 seconds) as demanded. I am using 8 threads with this.

**Comment by lperron** [comment]
still on master, 75s time limit:

CpSolverResponse summary:

status: FEASIBLE

objective: 564157

best_bound: 178618

booleans: 38884

conflicts: 0

branches: 77026

propagations: 6229195

integer_propagations: 3414919

restarts: 76999

lp_iterations: 15952

walltime: 75.5438

usertime: 75.5438

deterministic_time: 48.217

primal_integral: 599.737

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 28 juin 2021 à 10:12, Username159 ***@***.***> a
écrit :

**Comment by lperron** [comment]
60 s:

CpSolverResponse summary:
status: FEASIBLE
objective: 579963
best_bound: 178448
booleans: 38884
conflicts: 0
branches: 77022
propagations: 6229192
integer_propagations: 3414884
restarts: 76997
lp_iterations: 13598
walltime: 60.4385
usertime: 60.4385
deterministic_time: 43.532
primal_integral: 541.133

**Comment by Username159** [comment]
time_limit = 60*60 seconds
max_number_of_solutions = 500
threads = 16


The time limit was reached 45 minutes ago, but the solver still has not stopped.
Also the RAM is still quite high (about 60%).
During the optimization it was always between 45%-62% RAM memory.

It happened before that the solver took quite a while (around 20 minutes...) to stop after reaching the time limit or the max. number of wanted solutions, but 45 minutes (and still ongoing) is quite a long time...

![solver_not_stopping](https://user-images.githubusercontent.com/80465506/124110539-9ec38600-da68-11eb-8c8a-f74485303974.png)

Still have no idea why this is happening sometimes.
Maybe I just disable the subsolvers one by one and observe if something changes.

**Comment by lperron** [comment]
Are you using master or the latest release ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 1 juil. 2021 à 12:38, Username159 ***@***.***> a
écrit :

**Comment by Username159** [comment]
Name: ortools
Version: 9.0.9048
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google LLC
Author-email: or-tools@google.com
License: Apache 2.0


I just installed it with pip.

**Comment by lperron** [comment]
So we made substantial improvements on master.
This is what I get on my current run with 16 workers after 20 minutes:

#391   1275.78s best:278680 next:[179007,278679] rnd_var_lns_default(d=0.71
s=3741 t=0.10 p=0.50)
#Bound 1280.47s best:278680 next:[179008,278679] lb_tree_search #nodes:260
#392   1281.76s best:278622 next:[179008,278621]
graph_var_lns_default(d=0.12 s=3761 t=0.10 p=0.50)

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 1 juil. 2021 à 13:18, Username159 ***@***.***> a
écrit :

**Comment by lperron** [comment]
and after 1h:

CpSolverResponse summary:
status: FEASIBLE
objective: 273685
best_bound: 179016
booleans: 42745
conflicts: 11082
branches: 104737
propagations: 22934122
integer_propagations: 16315495
restarts: 76998
lp_iterations: 2568037
walltime: 3600.16
usertime: 57461.5
deterministic_time: 11822
primal_integral: 135527

So I assume the problem is solved on master.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Username159** [comment]
I am using the master version (Version: 9.0.9140) now and still have the same problems. 

I changed the model a little bit (mainly the input data that should be optimized), but I can't attach the newest model in proto format, so I attached a zip-archive containing the issue2604.pb.txt file.
[model.zip](https://github.com/google/or-tools/files/6753787/model.zip)

Time limit is 7 minutes, solver currently still running for 30 minutes now...

**Comment by lperron** [comment]
master, 420s time limit

CpSolverResponse summary:
status: FEASIBLE
objective: 1252259
best_bound: 141814
booleans: 186130
conflicts: 1
branches: 20367
propagations: 9944032
integer_propagations: 6762699
restarts: 20275
lp_iterations: 45769
walltime: 424.5
usertime: 424.5
deterministic_time: 1036.51
primal_integral: 14404.3
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 2 juil. 2021 à 11:55, Username159 ***@***.***> a
écrit :

**Comment by Username159** [comment]
I run the program on a different computer (also Linux Manjaro 20.2.1) and had the same problem.

With a 420 seconds time limit I got after 1.5 hours the following output and log protocol:




_ _ _ _ _ _ _Instantiating model starts at: 2021-07-02 14:41:51.316867_ _ _ _ _ _ _ _


Energy = 14417
Horizon = 14586
hinting: starts - new way
hinting: starts - new way


_ _ _ _ _ _ _Solver starts at: 2021-07-02 **14:43:16.971423**_ _ _ _ _ _ _ _



Starting CP-SAT solver.
Parameters: **max_time_in_seconds: 420** log_search_progress: true presolve_probing_deterministic_time_limit: 50 
search_branching: PORTFOLIO_SEARCH num_search_workers: 16 max_presolve_iterations: 12 hint_conflict_limit: 800 repair_hint: true

Initial optimization model '':
Search strategy: on 243 variables, CHOOSE_LOWEST_MIN, SELECT_MIN_VALUE
Search strategy: on 510 variables, CHOOSE_LOWEST_MIN, SELECT_MIN_VALUE
#Variables: 87885 (39892 in objective)
  - 192 different domains in [-43800,43800] with a largest complexity of 57.
  - 1 constants in {0} 
#kBoolOr: 78276 (#enforced: 78276) (#literals: 78276)
#kCircuit: 9
#kIntMax: 244
#kInterval: 510 (#enforced: 510)
#kLinear1: 88447 (#enforced: 88430)
#kLinear2: 119989 (#enforced: 118944)
#kLinear3: 32
#kLinearN: 421 (#terms: 4134)
#kNoOverlap: 9 (#intervals: 510, #optional: 510, #variable_sizes: 510)

Starting presolve at 0.05s
[Probing] deterministic_time: 1.00001 (limit: 1) wall_time: 1.21766 (Aborted 10197/201810)
[Probing]  - new fixed Boolean: 1552 (5280/201810)
[Probing]  - new integer holes: 4308
[Probing]  - new integer bounds: 534
[Probing]  - new binary clause: 15890
[SAT presolve] num removable Booleans: 1617 / 92316
[SAT presolve] num trivial clauses: 0
[SAT presolve] [0s] clauses:85866 literals:171908 vars:43553 one_side_vars:34499 simple_definition:8704 singleton_clauses:0
[SAT presolve] [0.0119423s] clauses:85866 literals:171908 vars:43553 one_side_vars:34499 simple_definition:8704 singleton_clauses:0
[SAT presolve] [0.0170802s] clauses:85726 literals:171488 vars:43518 one_side_vars:34499 simple_definition:8774 singleton_clauses:0
[MaxClique] Merged 85690(171380 literals) into 81294(162588 literals) at_most_ones.

Presolve summary:
  - 13958 affine relations were detected.
  - 8860 variable equivalence relations were detected.
  - rule 'affine: new relation' was applied 9940 times.
  - rule 'at_most_one: transformed into max clique.' was applied 1 time.
  - rule 'bool_and: non-reified.' was applied 1 time.
  - rule 'bool_or: implications' was applied 78276 times.
  - rule 'bool_or: only one literal' was applied 132 times.
  - rule 'bool_or: removed enforcement literal' was applied 8 times.
  - rule 'circuit: removed false arcs.' was applied 24 times.
  - rule 'deductions: 215812 stored' was applied 1 time.
  - rule 'dual: reduced domain' was applied 35724 times.
  - rule 'false enforcement literal' was applied 2404 times.
  - rule 'int_max: converted to equality' was applied 39 times.
  - rule 'int_max: converted to lin_max' was applied 205 times.
  - rule 'int_max: reduced domains' was applied 243 times.
  - rule 'int_max: removed variables' was applied 40 times.
  - rule 'interval: reduced domains' was applied 8 times.
  - rule 'lin_max: converted to equality' was applied 4 times.
  - rule 'lin_max: removed exprs' was applied 5 times.
  - rule 'lin_max: target domain reduced' was applied 7 times.
  - rule 'linear: always true' was applied 522 times.
  - rule 'linear: divide by GCD' was applied 8616 times.
  - rule 'linear: dual fixing' was applied 3536 times.
  - rule 'linear: empty' was applied 7455 times.
  - rule 'linear: extracted enforcement literal' was applied 200 times.
  - rule 'linear: fixed or dup variables' was applied 8685 times.
  - rule 'linear: infeasible' was applied 132 times.
  - rule 'linear: negative reified and' was applied 4488 times.
  - rule 'linear: positive equal one' was applied 446 times.
  - rule 'linear: positive reified and' was applied 4480 times.
  - rule 'linear: remapped using affine relations' was applied 11502 times.
  - rule 'linear: simplified rhs' was applied 79696 times.
  - rule 'linear: size one' was applied 61 times.
  - rule 'linear: small Boolean expression' was applied 4 times.
  - rule 'linear: split boxed constraint' was applied 84 times.
  - rule 'objective: variable not used elsewhere' was applied 3938 times.
  - rule 'presolve: iteration' was applied 1 time.
  - rule 'true enforcement literal' was applied 438 times.
  - rule 'variables with 2 values: create encoding literal' was applied 4431 times.
  - rule 'variables with 2 values: new affine relation' was applied 4431 times.
  - rule 'variables: detect half reified value encoding' was applied 85832 times.

Presolved optimization model '':
Search strategy: on 242 variables, CHOOSE_LOWEST_MIN, SELECT_MIN_VALUE
Search strategy: on 502 variables, CHOOSE_LOWEST_MIN, SELECT_MIN_VALUE
#Variables: 77514 (35949 in objective)
  - 299 different domains in [-1,14586] with a largest complexity of 57.
  - 1 constants in {1} 
#kBoolAnd: 509 (#enforced: 509) (#literals: 76898)
#kBoolOr: 36 (#literals: 108)
#kCircuit: 9
#kExactlyOne: 446 (#literals: 4163)
#kInterval: 510 (#enforced: 502)
#kLinMax: 201
#kLinear1: 71478 (#enforced: 71478)
#kLinear2: 116864 (#enforced: 116864)
#kLinear3: 502 (#enforced: 502)
#kNoOverlap: 9 (#intervals: 510, #optional: 502, #variable_sizes: 502)

Preloading model.
#Bound   5.51s best:inf   next:[125884,31203874] initial_domain

Starting Search at 5.62s with 16 workers and subsolvers: [ default_lp, fixed, pseudo_costs, no_lp, max_lp, core, quick_restart, quick_restart_no_lp, 
probing, lb_tree_search, feasibility_pump, rnd_var_lns_default, rnd_cst_lns_default, graph_var_lns_default, graph_cst_lns_default, scheduling_time_window_lns_default, 
scheduling_random_lns_default, rins_lns_default, rens_lns_default ]
#Bound  11.76s best:inf   next:[125884,31203842] core initial_propagation
#Bound  21.45s best:inf   next:[126238,31203842] max_lp initial_propagation
#1     334.06s best:1297659 next:[126238,1297658] quick_restart [repaired] fixed_bools:10/189772
Solution 0, time = 334.129954 s, objective = 1297659, makespan = 6337, transition cost = 6343, start times = 304145, posted job starts = 30463, overdue time = 68703
#2     336.44s best:1297645 next:[126238,1297644] rnd_var_lns_default(d=0.50 s=512 t=0.10 p=0.00)
Solution 1, time = 336.521931 s, objective = 1297645, makespan = 6337, transition cost = 6343, start times = 304143, posted job starts = 30463, overdue time = 68701
#3     349.20s best:1295934 next:[126238,1295933] graph_var_lns_default(d=0.19 s=528 t=0.10 p=0.00)
Solution 2, time = 349.278756 s, objective = 1295934, makespan = 6337, transition cost = 6343, start times = 303581, posted job starts = 30452, overdue time = 68703
#4     351.91s best:1293913 next:[126238,1293912] graph_cst_lns_default(d=0.46 s=529 t=0.10 p=0.50)
Solution 3, time = 351.977617 s, objective = 1293913, makespan = 6337, transition cost = 6343, start times = 303354, posted job starts = 30452, overdue time = 68368
#5     390.25s best:1293850 next:[126238,1293849] rnd_cst_lns_default(d=0.53 s=576 t=0.10 p=0.44)
Solution 4, time = 390.335203 s, objective = 1293850, makespan = 6337, transition cost = 6343, start times = 303345, posted job starts = 30452, overdue time = 68359
#6     396.98s best:1293731 next:[126238,1293730] rnd_var_lns_default(d=0.65 s=582 t=0.10 p=0.50)
**Solution 5, time = 397.041012 s**, objective = 1293731, makespan = 6337, transition cost = 6343, start times = 303328, posted job starts = 30452, overdue time = 68342

Sub-solver search statistics:
  'max_lp':
     LP statistics:
       final dimension: 204042 rows, 282499 columns, 907463 entries with magnitude in [6.881621e-04, 1.000000e+00]
       total number of simplex iterations: 2000
       num solves: 
         - #DUAL_FEASIBLE: 1
       managed constraints: 204042
       merged constraints: 31936
       shortened constraints: 11
       total cuts added: 0 (out of 0 calls)

  'lb_tree_search':
     LP statistics:
       final dimension: 1000 rows, 79457 columns, 24247 entries with magnitude in [6.311944e-02, 1.000000e+00]
       total number of simplex iterations: 1221
       num solves: 
         - #OPTIMAL: 2
         - #DUAL_FEASIBLE: 1
       managed constraints: 204042
       merged constraints: 31936
       shortened constraints: 11
       num simplifications: 1
       total cuts added: 0 (out of 0 calls)


Solutions found per subsolver:
  'graph_cst_lns_default': 1
  'graph_var_lns_default': 1
  'quick_restart': 1
  'rnd_cst_lns_default': 1
  'rnd_var_lns_default': 2

Objective bounds found per subsolver:
  'core': 1
  'initial_domain': 1
  'max_lp': 1

CpSolverResponse summary:
status: FEASIBLE
objective: 1293731
best_bound: 126238
booleans: 187437
conflicts: 2
branches: 20022
propagations: 9923352
integer_propagations: 6696726
restarts: 20022
lp_iterations: 2000
walltime: 5262.54
usertime: 5262.54
deterministic_time: 352.874
primal_integral: 4999.43

status: FEASIBLE
End of Solve-section

  Job 0 starts at 11 (alt 2, duration 6) and ends at 17 with rank 4 on machine 2
  Job 1 starts at 678 (alt 7, duration 347) and ends at 1025 with rank 18 on machine 7
  ...
  Job 241 starts at 12 (alt 6, duration 2) and ends at 14 with rank 5 on machine 6
  Job 242 starts at 4646 (alt 1, duration 1) and ends at 4647 with rank 52 on machine 1
Solve status: FEASIBLE
Objective value: 1293731
Makespan: 6337

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ Optimization stops at: 2021-07-02 **16:11:00.535955**_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by Username159** [comment]
So I thought I found the problem in a solver parameter and set everything back to default and it worked fine yesterday.
Today I switched to new data, and same problem as before.

Using 16 threads (around 20% RAM memory), a time limit of 3600 seconds and a max_num_of_solutions of 500.

The last output I get is:
```
#Bound 1015.83s best:779080 next:[520664,779079] lb_tree_search #nodes:177
#177   1018.69s best:778985 next:[520664,778984] rnd_var_lns_default(d=0.80 s=51196 t=0.12 p=0.50)
...
#Bound 3050.93s best:778985 next:[520925,778984] lb_tree_search #nodes:1894
#Bound 3061.45s best:778985 next:[521115,778984] max_lp
#Bound 3062.04s best:778985 next:[521122,778984] max_lp
#Bound 3062.13s best:778985 next:[521195,778984] max_lp
#Bound 3062.44s best:778985 next:[521196,778984] max_lp
```

and after that the solver is stuck.

Tried it several times and on different machines and waited up to 3 hours over the time limit, but it get stuck everytime.

Updated model proto:
[issue2604.pb.txt](https://github.com/google/or-tools/files/6777265/issue2604.pb.txt)

**Comment by lperron** [comment]
Thanks for your patience. I can reproduce the stalling of the search.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 7 juil. 2021 à 15:02, Username159 ***@***.***> a
écrit :
