### ISSUE TITLE
java: linear solver memory leak

### ISSUE THREAD

**Issue by mtetreau** [google/or-tools#3684]
java: heap memory consumption
version: 9.4

There is an issue regarding the implementation of ortools-java classes `com.google.ortools.linearsolver.MPConstraint` and `com.google.ortools.linearsolver.MPVariable`. 

Both classes override the deprecated method finalize() resulting in a significant and unnecessary consumption of heap memory and process time. A 50% reduction of heap memory and 20% reduction of process time have been observed in our tests when removing those methods, since related instances were not map nor treated by the jvm finalizer.

Since in java, there is no control on when finalize() is called by garbage collection, a better practice to clean resources would probably be to explicitly call MPVariable.delete()/MPConstraint.delete() if needed.

Thank you for ortools!

**Comment by lperron** [comment]
this is swig generated code. Not sure what we can do.

**Comment by mtetreau** [comment]
Unfortunately, our solver connector is too generic and cannot be easily simplified to use modelbuilder. 

Thank you, it allowed us to learn about this api!

**Comment by Opsiana** [comment]
Hi Laurent --
I am afraid that I am seeing an issue that is consistent with what mtetreau describes. We are running or-tools with Java in a Docker container on GCP cloud Run. The memory utilization profile of the container goes up when a large instance is solved, and does not revert to initial levels after the request is completed. I have used a heap profiler to confirm that a lot of memory remains allocated to MPvariable and MPconstraint. Eventually the container crashes, most often in the middle of a calculation.

**Comment by yasha-spare** [comment]
I'm seeing similar behaviour:

- App is a JVM vehicle routing problem solver
- In one stage of the solving, that gets run very regularly, it solves a small linear equation, using `com.google.ortools.linearsolver.MPSolver.createSolver("CLP")`
  - These are pretty small problems, created and solved in about 1ms each, there's just an absolute tonne of them being solved over time
- If the app gets too busy, all the memory starts to get consumed by OR tools `MPVariable` and `MPConstraint` instances:

![image](https://github.com/google/or-tools/assets/78819967/c35f44d4-e079-4abd-afde-b02ded27c070)
![image](https://github.com/google/or-tools/assets/78819967/28db0378-5600-49f6-962a-eda4f56f8bd7)

Like @Opsiana I'm also on `9.7.2996` of `ortools-java`, and Java 17.  Seems like a memory leak, but it's very clear from the code I'm not keeping around any references to OR tools objects - the model gets built, solved, then immediately transformed into a totally different representation, with no references to the OR tools classes hanging around.  Anyone found a workaround/solution?

**Comment by yasha-spare** [comment]
For anyone else reading this - we ended up solving this by switching off of or-tools, to clp-java (https://github.com/quantego/clp-java).  We were using CLP under the hood anyways with or-tools, so they're both just Java wrappers of the same underlying native lib.  Behaviour and performance seems to be identical between the two (for our use case, at least), but with clp-java memory usage stays constant and low, even under really heavy load, while with or-tools under identical load memory climbed straight up until OOM.

**Comment by ClaudioConsolmagno** [comment]
I have ended up solving my issue 2 ways: I did move to ModelBuilder (is there Java docs on it btw? Had to figure out lots of things myself), and it did help a lot. Instead of my server crashing about twice a day, it started crashing once every 2 days.

So moving to ModelBuilder alone did not fix the issue. What really did fix it (and it's been running fine for over a week with a lot more reasonable memory consumption) was setting these jvm flags: `-XX:+UnlockExperimentalVMOptions -XX:TrimNativeHeapInterval=60000`. Have also set env flag `MALLOC_ARENA_MAX = 2` but not sure that was strictly necessary.

As I understand, the native code under or-tools uses the `malloc` OS function to allocate large areas of memory (arenas) and the default `malloc` doesn't let go of memory very easily with some sort of fragmentation problem. Setting `-XX:TrimNativeHeapInterval=60000` runs a "trim" command every minute and that sort of forces unused off-heap memory to be released.

So if you are running the solver lots of times, memory gets allocated and de-allocated within those arenas but don't necessarily get released back to the OS due fragmentation and some technical reasons I don't fully understand.

This flag is only available since Java 17 so if you're on <17, setting `MALLOC_ARENA_MAX = 2` (default is generally `4` afaik) may help. But from my research the best thing to do regardless of Java version is to setup a different allocator function like jemalloc (described in a devoxx talk in the youtube link below). That should work even better than the flag and works for any Java version. I didn't go there though since the flag was enough for my use case.

Some resources if anybody wants to know more:

https://www.algolia.com/blog/engineering/when-allocators-are-hoarding-your-precious-memory/
https://stackoverflow.com/a/28935176/9994213
https://github.com/openjdk/jdk/pull/14781
https://github.com/openjdk/jdk/pull/17799
https://github.com/prestodb/presto/issues/8993
https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior
https://github.com/redhat-developer/vscode-java/issues/3395
https://www.youtube.com/watch?v=c755fFv1Rnk&t=2046s

I hope this helps and maybe even helps or-tools developers find a way to get around this issue.

**Comment by tkz2020** [comment]
The CpSolver we use has always had memory leak problems. Has anyone encountered similar problems?

**Comment by lperron** [comment]
CP-SAT?

Le mar. 23 avr. 2024, 04:13, tukangzheng ***@***.***> a
écrit :

**Comment by tkz2020** [comment]
yes

**Comment by lperron** [comment]
CP-SAT does not leak memory.
It uses a lot of memory, but does not leak.

Le mer. 24 avr. 2024, 10:40, tukangzheng ***@***.***> a
écrit :

**Comment by mtetreau** [comment]
@Mizux, from what we have observed, it was not a memory leak. 

Just an avoidable consumption of memory used by the java.lang.ref.Finalizer thread and triggered by the presence of the finalize() method on MPConstraint/MPVariable classes.

May be the issue title should then be: 'java: linear solver memory bloat'

**Comment by Pikulo** [comment]
> 我们用的CpSolver一直有内存泄漏问题。有人遇到过类似问题吗？
遇到了
